# site settings
title: Curitiba Psicologia e Arte
subtitle: 
email: contato@curitibapsicologiaearte.com.br
description: A terapia busca tratar da alma antes que ela adoeça. Quando realizada com profissionais qualificados, melhora a qualidade de vida do paciente, aumentando seu autoconhecimento e sua capacidade de lidar com seus próprios problemas e emoções.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Rua Sete de Abril, 440 - Alto da XV
city: Curitiba 
state: PR
zip_code: 82590-300
country: Brasil
phone: (41) 9 9842-0923

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url: https://www.facebook.com/curitibapsicologiaearte/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/curitibapsicologiaearte/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
  
  exclude:
  - vendor
